apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naHRrLnZuIjp7ImF1dGgiOiJZMmxqWkRwaVpWWlhORlUwUm5Sa1RIVjRjbFExVGpKT1JYaERWMVU9In0sInJlZ2lzdHJ5LmdpYW9oYW5ndGlldGtpZW0udm4iOnsiYXV0aCI6IlkybGpaRHBXTm1aWk1rZGxVVTVFYmxwNlpXMUVRRUp1ZDJKbWEybz0ifX19
immutable: false
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson